cisco-open/forge

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/default_pr.md
Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.
Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.
=> feat: add templates for issues and prs

.docker/pre-commit/Dockerfile, .github/workflows/build-pre-commit.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml
This PR will add pre-commit docker and pipeline to build it
=> ci: add pre-commit docker and pipeline

modules/infra/eks/README.md, modules/infra/eks/karpenter.tf, modules/infra/eks/templates/ec2_node_class.yaml.tpl, modules/infra/eks/templates/node_pool.yaml.tpl
This PR will fix karpenter config for nodepool
=> fix: fix karpenter config for eks

README.md
Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.
Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.
=> docs: improve README with better context

build/ansible/build_gh_base_image.yaml, build/ansible/group_vars/all/common.yaml, build/ansible/requirements.yml, build/ansible/roles/deps/tasks/apt.yml, build/ansible/roles/deps/tasks/clean.yml, build/ansible/roles/deps/tasks/cli-tools.yml, build/ansible/roles/deps/tasks/docker.yml, build/ansible/roles/deps/tasks/gh.yml, build/ansible/roles/deps/tasks/main.yml, build/ansible/roles/splunk_otel_collector/tasks/main.yml, build/ansible/roles/teleport/files/start-teleport.sh, build/ansible/roles/teleport/files/teleport.service, build/ansible/roles/teleport/tasks/main.yml, build/ansible/roles/teleport/templates/teleport.yaml.j2
Add initial Ansible roles to build the Forge base AMI.
=> feat: add ansible roles to build forge base image

README.md
Refactored README for clarity, conciseness, and improved onboarding experience.
=> docs(README): simplify wording and structure for clarity

.pre-commit-config.yaml, modules/infra/forge_subscription/ecr.tf, modules/infra/forge_subscription/providers.tf, modules/infra/forge_subscription/variables.tf, scripts/update-terraform-docs.sh
Allow tenants to pull ECR repos from different regions
=> feat: allow tenants to subscribe to different regions

modules/platform/forge_runners/README.md, modules/platform/forge_runners/lambda/github_app_runner_group.py, modules/platform/forge_runners/register_repo_runner_group.tf
Update lambda function to create runner group if is not created
=> feat: add function to create runner group if is not created

modules/platform/forge_runners/lambda/github_app_runner_group.py, modules/platform/forge_runners/register_repo_runner_group.tf
Fix lambda for runner group sync to be used in GH onprem
=> fix: allow runner group sync to work in onprem

.github/workflows/build-forge-github-app-register.yml, forge-github-app-register/.dockerignore, forge-github-app-register/Dockerfile, forge-github-app-register/app.py, forge-github-app-register/deploy/github-app/app-manifest.json, forge-github-app-register/deploy/github-app/register.html, forge-github-app-register/requirements.txt, modules/core/arc/README.md, modules/core/arc/scale_set/README.md, modules/infra/ami_policy/README.md, modules/infra/ami_sharing/README.md, modules/infra/billing/README.md, modules/infra/budget/README.md, modules/infra/cloud_custodian/README.md, modules/infra/cloud_formation/README.md, modules/infra/ecr/README.md, modules/infra/eks/README.md, modules/infra/opt_in_regions/README.md, modules/infra/secrets/README.md, modules/infra/service_linked_roles/README.md, modules/infra/storage/README.md, modules/integrations/splunk_cloud_conf_shared/README.md, modules/integrations/splunk_o11y_aws_integration/README.md, modules/integrations/splunk_o11y_aws_integration_common/README.md, modules/integrations/teleport/README.md, modules/integrations/teleport/tenant/README.md, modules/platform/ec2_deployment/README.md, modules/platform/forge_runners/README.md
Add dockerfile and python script to automated the GH app creation with everything that is needed
=> feat: add code helper to automated gh app creation

examples/deployments/extras/release_versions.yaml, examples/deployments/extras/terragrunt/_global_settings/_global.hcl, examples/deployments/extras/terragrunt/_global_settings/cloud_custodian.hcl, examples/deployments/extras/terragrunt/_global_settings/cloud_formation.hcl, examples/deployments/extras/terragrunt/_global_settings/ecr.hcl, examples/deployments/extras/terragrunt/_global_settings/forge_subscription.hcl, examples/deployments/extras/terragrunt/_global_settings/storage.hcl, examples/deployments/extras/terragrunt/environments/prod/_environment_wide_settings/_environment.hcl, examples/deployments/extras/terragrunt/environments/prod/cloud_custodian/config.hcl, examples/deployments/extras/terragrunt/environments/prod/cloud_custodian/terragrunt.hcl, examples/deployments/extras/terragrunt/environments/prod/cloud_formation/terragrunt.hcl, examples/deployments/extras/terragrunt/environments/prod/forge_subscription/subscription_settings.hcl, examples/deployments/extras/terragrunt/environments/prod/forge_subscription/terragrunt.hcl, examples/deployments/extras/terragrunt/environments/prod/regions/eu-west-1/_region_wide_settings/_region.hcl, examples/deployments/extras/terragrunt/environments/prod/regions/eu-west-1/ecr/config.hcl, examples/deployments/extras/terragrunt/environments/prod/regions/eu-west-1/ecr/terragrunt.hcl, examples/deployments/extras/terragrunt/environments/prod/storage/terragrunt.hcl, examples/deployments/extras/terragrunt/environments/safety_hook.sh, examples/deployments/extras/terragrunt/environments/terragrunt.hcl, examples/deployments/splunk-deployment/release_versions.yaml
This PR adds deployment examples for extra modules
=> docs: add examples for extra modules

modules/core/arc/scale_set/template_files/dind.yml.tftpl, modules/core/arc/scale_set/template_files/k8s.yml.tftpl, modules/platform/ec2_deployment/main.tf
This PR will remove the log group creation of unused logs
=> deprecated: remove unused logs from cloudwatch

docs/configurations/build/gh_base_image.md, docs/configurations/index.md, examples/build/ansible/group_vars/all/common.yaml
Add doc how to build packer for gh base image example
=> docs: add docs how build gh base image

modules/core/arc/README.md, modules/core/arc/scale_set/README.md, modules/core/arc/scale_set/template_files/dind.yml.tftpl, modules/core/arc/scale_set/versions.tf, modules/core/arc/scale_set_controller/README.md, modules/core/arc/scale_set_controller/versions.tf, modules/core/arc/versions.tf, modules/integrations/splunk_cloud_conf_shared/README.md, modules/integrations/splunk_cloud_conf_shared/versions.tf, modules/integrations/teleport/README.md, modules/integrations/teleport/versions.tf, modules/platform/ec2_deployment/README.md, modules/platform/ec2_deployment/versions.tf, modules/platform/forge_runners/README.md, modules/platform/forge_runners/versions.tf
This PR fixes breaking changes in aws and helm providers by using older version
Also fixes pod identity in dind containers
=> fix: fix providers

.pre-commit-config.yaml, examples/deployments/forge-eks/release_versions.yaml, examples/deployments/forge-eks/terragrunt/_global_settings/eks_secrets.hcl, examples/deployments/forge-eks/terragrunt/environments/prod/eks_secrets/config.hcl, examples/deployments/forge-eks/terragrunt/environments/prod/eks_secrets/config.yaml, examples/deployments/forge-eks/terragrunt/environments/prod/eks_secrets/terragrunt.hcl, examples/deployments/forge-eks/terragrunt/environments/prod/regions/eu-west-1/eks/config.hcl, examples/deployments/forge-eks/terragrunt/environments/prod/regions/eu-west-1/eks/config.yaml, examples/templates/eks/eks/config.yaml
This PR update eks example by adding property `cluster_volume`
=> docs: update eks template

modules/integrations/splunk_aws_billing/billing_per_resource_process.tf, modules/integrations/splunk_aws_billing/billing_per_service.tf, modules/integrations/splunk_aws_billing/secrets.tf, modules/integrations/splunk_o11y_aws_integration/cf.tf, modules/integrations/splunk_o11y_aws_integration/secrets.tf, modules/integrations/splunk_otel_eks/otel.tf, modules/integrations/splunk_otel_eks/secrets.tf, modules/integrations/splunk_secrets/main.tf
This PR will create new splunk secrets to different type of metrics
=> feat: create splunk token per type of logs and metrics

modules/infra/eks/karpenter.tf
This PR prevents Karpenter from recreating the IAM policy on every apply.
=> fix: remove dependencies for kapenter

modules/platform/ec2_deployment/scripts/download_lambdas.sh
This PR updates the bash script to download correct version of lambda functions
=> chore: update lambda versions

modules/core/arc/README.md, modules/core/arc/scale_set/README.md, modules/infra/ami_policy/README.md, modules/infra/ami_sharing/README.md, modules/infra/cloud_custodian/README.md, modules/infra/cloud_custodian/main.tf, modules/infra/cloud_formation/README.md, modules/infra/ecr/README.md, modules/infra/eks/eks.tf, modules/infra/opt_in_regions/README.md, modules/infra/service_linked_roles/README.md, modules/integrations/splunk_cloud_conf_shared/README.md, modules/platform/ec2_deployment/README.md, modules/platform/forge_runners/README.md
This PR will add permission to delete volumes by cloud custodian
=> feat: add permission to delete volumes by custodian

.docker/forge-github-app-register/deploy/github-app/app-manifest.json, modules/platform/forge_runners/update_gh_app.tf
This PR will fix the json config to create new GH app and update terraform script to trigger github app update when github org has changed
=> fix: remove write permission for org level

modules/core/arc/README.md, modules/core/arc/karpenter.tf, modules/core/arc/scale_set/README.md, modules/infra/ami_policy/README.md, modules/infra/ami_sharing/README.md, modules/infra/cloud_custodian/README.md, modules/infra/cloud_formation/README.md, modules/infra/ecr/README.md, modules/infra/eks/calico.tf, modules/infra/eks/karpenter.tf, modules/infra/opt_in_regions/README.md, modules/infra/service_linked_roles/README.md, modules/integrations/splunk_cloud_conf_shared/README.md, modules/integrations/splunk_o11y_aws_integration/README.md, modules/integrations/splunk_o11y_aws_integration_common/README.md, modules/integrations/splunk_otel_eks/README.md, modules/integrations/teleport/README.md, modules/integrations/teleport/tenant/README.md, modules/platform/ec2_deployment/README.md, modules/platform/forge_runners/README.md
This PR fixes a race condition when deploying multiple eks cluster
=> fix: add context in kubectl to prevent race condition in apply

modules/core/arc/README.md, modules/core/arc/karpenter.tf, modules/core/arc/templates/node_pool.yaml.tpl, modules/core/arc/versions.tf, modules/infra/eks/karpenter.tf
This PR add ec2nodeclass per tenant and add support for cluster migration in karpenter config per tenant
=> feat: add EC2NodeClass per tenant

modules/core/arc/README.md, modules/core/arc/karpenter.tf
This PR fixes an edge issue: when the EKS API may response a bit slow, ec2nodeclasses cannot be deleted and it stuck the deployment
=> fix: use loop to prevent stuck during terraform apply

modules/core/arc/README.md, modules/core/arc/karpenter.tf, modules/core/arc/scale_set/README.md, modules/infra/ami_policy/README.md, modules/infra/ami_sharing/README.md, modules/infra/cloud_custodian/README.md, modules/infra/cloud_formation/README.md, modules/infra/ecr/README.md, modules/infra/eks/README.md, modules/infra/opt_in_regions/README.md, modules/infra/service_linked_roles/README.md, modules/integrations/splunk_cloud_conf_shared/README.md, modules/integrations/splunk_o11y_aws_integration/README.md, modules/integrations/splunk_o11y_aws_integration_common/README.md, modules/integrations/splunk_otel_eks/README.md, modules/integrations/teleport/README.md, modules/integrations/teleport/tenant/README.md, modules/platform/ec2_deployment/README.md, modules/platform/forge_runners/README.md
This PR will fix kubeconfig conflict with multiple-tenant deployment
=> fix: use individual kube config for each tenant

modules/integrations/splunk_cloud_data_manager/data_input/scripts/create_splunk_integration.sh, modules/integrations/splunk_cloud_data_manager/data_input/scripts/get_splunk_integration.sh
This PR will add a workaround for a bug in data manager input(splunk cloud)
=> fix: make a hotfix to allow to deploy splunk cloud integration

modules/core/arc/README.md, modules/core/arc/scale_set/README.md, modules/infra/ami_policy/README.md, modules/infra/ami_sharing/README.md, modules/infra/ami_sharing/main.tf, modules/infra/ami_sharing/variables.tf, modules/infra/cloud_custodian/README.md, modules/infra/cloud_formation/README.md, modules/infra/ecr/README.md, modules/infra/eks/README.md, modules/infra/opt_in_regions/README.md, modules/infra/service_linked_roles/README.md, modules/integrations/splunk_cloud_conf_shared/README.md, modules/integrations/splunk_o11y_aws_integration/README.md, modules/integrations/splunk_o11y_aws_integration_common/README.md, modules/integrations/splunk_otel_eks/README.md, modules/integrations/teleport/README.md, modules/integrations/teleport/tenant/README.md, modules/platform/ec2_deployment/README.md, modules/platform/forge_runners/README.md
This PR will allow to share multi type of AMI with other AWS accounts. Allowing to support multi base image for example
=> feat: allow to share multi type of images

modules/platform/ec2_deployment/template_files/user_data.tftpl
This PR will add support boot image using ubuntu 24.04
=> feat: add support to boot ubuntu 24.04

modules/platform/forge_runners/scripts/generate_and_patch_github_app.sh, modules/platform/forge_runners/update_gh_app.tf
This PR will enhance logs in script that updates github app with webhook and secrets preventing to silence failures
=> feat: make script to update github app more verbose

modules/integrations/splunk_cloud_data_manager/data_input/scripts/create_splunk_integration.sh, modules/integrations/splunk_cloud_data_manager/data_input/scripts/get_splunk_integration.sh, modules/integrations/splunk_cloud_data_manager/sec_meta.tf, modules/integrations/splunk_cloud_data_manager/sec_meta_ec2_tags/README.md, modules/integrations/splunk_cloud_data_manager/sec_meta_ec2_tags/data.tf, modules/integrations/splunk_cloud_data_manager/sec_meta_ec2_tags/lambda/sec_meta_ec2_tags.py, modules/integrations/splunk_cloud_data_manager/sec_meta_ec2_tags/main.tf, modules/integrations/splunk_cloud_data_manager/sec_meta_ec2_tags/variables.tf, modules/integrations/splunk_cloud_data_manager/sec_meta_ec2_tags/versions.tf, modules/integrations/splunk_o11y_aws_integration_common/README.md
This PR will create a specific Lambda function to handle EC2 tagging events and send them to Splunk Cloud.
=> feat: add new lambda function to handle ec2 tagging events for splunk cloud

modules/infra/eks/templates/node_pool.yaml.tpl
This PR will use better instance family in karpenter
=> feat: use better instance type

modules/platform/ec2_deployment/README.md, modules/platform/ec2_deployment/main.tf, modules/platform/ec2_deployment/scripts/download_lambdas.sh
This PR will update the terraform module `terraform-aws-github-runner` to `v6.7.8`
=> feat: update module terraform-aws-github-runner to v6.7.8
